// <auto-generated />
using System;
using MicroCoffees.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroCoffees.Api.Infrastructure.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20230329223843_Beans")]
    partial class Beans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroCoffees.Domain.Entities.CoffeeAggregate.Bean", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Roast")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Beans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8554579-efa2-4262-ba85-eafdd601b443"),
                            Name = "The Daily Standup",
                            Roast = 0
                        },
                        new
                        {
                            Id = new Guid("591c4786-c6b5-4c88-bb89-58ffd8330340"),
                            Name = "Null Reference Exception",
                            Roast = 1
                        },
                        new
                        {
                            Id = new Guid("c52b2291-ff7f-48fe-a164-6b91728aef91"),
                            Name = "Stack Overflow Response",
                            Roast = 2
                        });
                });

            modelBuilder.Entity("MicroCoffees.Domain.Entities.CoffeeAggregate.Coffee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BeanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeanId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("MicroCoffees.Domain.Entities.CoffeeAggregate.Coffee", b =>
                {
                    b.HasOne("MicroCoffees.Domain.Entities.CoffeeAggregate.Bean", "Bean")
                        .WithMany()
                        .HasForeignKey("BeanId");

                    b.Navigation("Bean");
                });
#pragma warning restore 612, 618
        }
    }
}
